apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        # Esto fuerza reinicio si cambian los metrics (útil para Prometheus)
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsUser: 1000 # Seguridad: No correr como root
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # VARIABLES DE ENTORNO
          env:
            - name: SPRING_DATASOURCE_URL       # Nombre nativo de Spring
                value: {{ .Values.env.dbUrl }}
                  - name: SPRING_DATASOURCE_USERNAME  # Nombre nativo de Spring
                    value: {{ .Values.env.dbUser }}
                  - name: SPRING_DATASOURCE_PASSWORD  # Nombre nativo de Spring
                    valueFrom:
                      secretKeyRef:
                        name: citasalud-db-secret
                        key: password
                  # Esto ayuda a ver errores de SQL si los hay
                  - name: SPRING_JPA_SHOW_SQL
                    value: "true"
          # HEALTH CHECKS (VITAL para K8s)
