apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        # Esto fuerza reinicio si cambian los metrics (útil para Prometheus)
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsUser: 1000 # Seguridad: No correr como root
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # VARIABLES DE ENTORNO
          env:
            - name: DB_URL
              value: {{ .Values.env.dbUrl }}
            - name: DB_USER
              value: {{ .Values.env.dbUser }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: citasalud-db-secret # <--- El secreto que crearemos manualmente
                  key: password
          # HEALTH CHECKS (VITAL para K8s)
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 180 # Dar tiempo a Spring para arrancar
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}